- name: Create static files directory
  file: path="{{ static_files_path_ }}" state=directory owner="{{ vagrant_login_user }}" group="{{ vagrant_login_user }}"
  become: true
  tags: [bower]

- name: Run collectstatic
  django_manage: >
    command=collectstatic
    app_path={{ django_path_ }}
    settings=config.settings.{{ env }}
    virtualenv={{ venv_path_ }}
  register: collectstatic_out

- debug: msg="{{ collectstatic_out }}"
