- name: Perform migrations
  django_manage: command=migrate app_path={{ django_path_ }} virtualenv={{ venv_path_ }}
  tags: [migrate]

- name: Insert fixtures
  django_manage: command=loaddata app_path={{ django_path_ }} fixtures={{ django_fixtures_ }} virtualenv={{ venv_path_ }}
  when: django_fixtures_ is defined
  tags: [fixtures]

- name: Create super user
  raw: . {{ environment_variables_file_ }} && echo "from db.users import StaffUser; StaffUser.objects.create_superuser(email='{{ superuser_email_ }}', password='{{ superuser_password_ }}')" | {{ venv_path_ }}/bin/python {{ django_path_ }}/manage.py shell
  when: superuser_email_ is defined and superuser_password_ is defined and environment_variables_file_ is defined
  tags: [createsuperuser]
