- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - npm

- name: Install npm packages
  npm: name={{ item }} global=yes
  with_items: "{{ npm_packages }}"

- name: Create symlink from 'node' to 'nodejs'
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
