---
- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify:
    - reload nginx

- name: Add namespaced vhost config files (if any are configured).
  template:
    src: "nginx-{{ item }}.conf.j2"
    dest: "{{ nginx_vhost_path }}/{{ item }}{{ vhost_namespace }}.conf"
    mode: 0644
  with_items: "{{ nginx_namespaced_vhosts }}"
  when: nginx_namespaced_vhosts|length > 0
  notify:
    - reload nginx

- name: Add vhost config files (if any are configured).
  template:
    src: "nginx-{{ item }}.conf.j2"
    dest: "{{ nginx_vhost_path }}/{{ item }}.conf"
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
  when: nginx_vhosts|length > 0
  notify:
    - reload nginx

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/vhosts.conf"
    state: absent
  when: nginx_vhosts|length == 0
  notify:
    - reload nginx

