branch-defaults:
  master:
    environment: 919_api_prod
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: 719s
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2017.09 v2.8.4 running Multi-container Docker 17.09.1-ce (Generic)
  default_region: us-west-2
  profile: null
  sc: git
