- name: "Copy over script files to scripts directory"
  template:
    src: "django_scripts-{{ item }}.j2"
    dest: "{{ scripts_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ scripts }}"
  when: scripts|length > 0

# The `shell` module can handle < redirects, unlike the `command` module
- name: "Run script files in the context of the Django shell"
  shell: "echo 'run {{ scripts_dir }}/{{ item }}' | {{ venv_path_ }}/bin/python {{ django_path_ }}/manage.py shell"
  with_items: "{{ scripts }}"
  when: scripts|length > 0
  register: django_scripts_out

- debug: msg="{{ django_scripts_out }}"

- name: "Remove script files"
  file:
    path: "{{ scripts_dir }}/{{ item }}"
    state: absent
  with_items: "{{ scripts }}"
  when: scripts|length > 0 and clean_up_scripts
