- name: Copy over cron scripts
  template:
    src: "cron-{{ item.script }}.j2"
    dest: "{{ cron_path }}/{{ item.script }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ scripts }}"
  when: scripts|length > 0

- name: Edit /etc/crontab to ensure that jobs execute
  lineinfile: dest=/etc/crontab regexp="^.*{{ item.script }}" line="{{ item.frequency }} {{ item.user }} {{ cron_path }}/{{ item.script }}"
  with_items: "{{ scripts }}"
  when: scripts|length > 0
