---
app_name: "mexicanos_unidos"
git_branch: "master"
bin_path: "/usr/local/bin"
vagrant_login_user: "vagrant"
base_website_url: ""

_env_all:
  CUSTOM_CONTACT_EMAIL: ""
  CUSTOM_CONTACT_PHONE: ""
  CUSTOM_CONTACT_ADDRESS: ""
  CUSTOM_DATABASE_PORT: "5432"
  CUSTOM_REDIS_PORT: "6379"
  CUSTOM_CELERY_PORT: "5555"

# this groups_vars file is loaded last, because all groups are descendants of "all"
# this means this file has access to all group_vars included in a given playbook
_env_combined: "{{ _env|combine(_env_all)|combine(_env_all_secret) }}"

repo_path: "/home/{{ login_user }}/{{ app_name }}"
django_path: "{{ repo_path }}/{{ app_name }}"
venv_path: "/opt/envs/{{ app_name }}"
