---
- include: backend_common.yml
  vars:
    dynamic_hosts: api

- hosts: api
  user: "{{ login_user }}"
  become: yes

  environment: "{{ _env_combined }}"

  roles:
    - role: django
      tags: [django]
      venv_path_: "{{ venv_path }}"
      django_path_: "{{ django_path }}"
      environment_variables_file_: "{{ django_path }}/.env"
      django_fixtures_: "care_tasks"
      # define superuser_email_ and superuser_password_ if you want to createsuperuser

    - role: upstart
      tags: [upstart]
      scripts: "{{ upstart_scripts_backend }}"
      service_namespace: "-{{ env }}"
      replace_logrotate: true

    # only for development, this avoids NFS lag when reloading django dev server
    - role: upstart
      tags: [upstart]
      shell_scripts: "django-reloader.py"
      shell_scripts_path: "{{ bin_path }}"
      scripts: "django-reloader"
      replace_logrotate: true
      when: env == "development"

    - role: logrotate
      tags: [logrotate]
      scripts: []
      crontab_frequency: "*/30 * * * *"

    - role: iptables
      tags: [iptables]
      firewall_allowed_tcp_ports:
        - "22"
        - "25"
      firewall_allowed_private_tcp_ports:
        - "8000"
      when: env != "development"

    - role: vagrant
      tags: [vagrant]
      when: env == "development"

# ansible working its magic on the host machine, the working directory is the directory from which
# the `ansible-playbook` is invoked, i.e. `/deploy`
- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Symlink hooks into .git/hooks directory on host machine
      shell: cd ../.git/hooks && ln -s -f ../../deploy/hooks/* ./
      tags: [git_hooks]
      when: env == "development"
