---
# this playbook provides common functionality for installing the django app on a server
- hosts: "{{ dynamic_hosts }}"
  user: "{{ login_user }}"
  become: yes

  environment: "{{ _env_combined }}"

  roles:
    - role: apt
      update: true
      packages: "{{ application_apt_packages }}"

    # repo is not cloned in development because NFS takes care of sharing the repo with VM
    - role: clone_repo
      tags: [clone_repo]
      source: "https://{{ github_user }}:{{ github_password }}@github.com/919MX/backend.git"
      target: "{{ repo_path }}"
      git_branch_: "{{ git_branch }}"
      git_force_: yes
      when: env != "development"

    - role: virtualenv
      tags: [virtualenv]
      path: "{{ venv_path }}"
      requirements_files_path: "{{ django_path }}"
      requirements_files: "{{ requirements_files_ }}"
      user: "{{ login_user }}"
      group: "{{ login_user }}"

    - role: env_vars
      tags: [env_vars]
      environment_variables: "{{ _env_combined }}"
      environment_variables_file: "{{ django_path }}/.env"
      startup_file: "/home/{{ login_user }}/.bash_profile"
