---
- hosts: webserver
  user: "{{ login_user }}"
  become: yes

  tasks:
    - name: "Remove docs document root if it exists: {{ docs_path }}"
      file: path="{{ docs_path }}" state=absent
      tags: [clean]
    - name: "Create docs document root"
      file: path="{{ docs_path }}" state=directory owner="{{ login_user }}" group="{{ login_user }}" mode=0755 # target directory must be executable for `rsync` to work
      tags: [clean]


- hosts: localhost
  connection: local

  vars:
    local_docs_path: "../docs"
    local_docs_build_path: "{{ local_docs_path }}/build/" # trailing / copies contents of directory, without copying directory

  tasks:
    - name: "Build documentation site files"
      raw: cd {{ local_docs_path }} && mkdocs build --clean
      register: mk_docs_out
      tags: [build]

    - debug: msg="{{ mk_docs_out }}"
      tags: [build]

    # much faster than `copy` for directories
    - name: "Copy over documentation site"
      raw: rsync -a -e 'ssh -i ~/.ssh/asistia_nginx' {{ local_docs_build_path }} {{ login_user }}@{{ groups['webserver'][0] }}:{{ docs_path }}
      register: rsync_out
      tags: [rsync]

    - debug: msg="{{ rsync_out }}"
      tags: [rsync]
