---
- include: backend_common.yml
  vars:
    dynamic_hosts: message

- hosts: message
  user: "{{ login_user }}"
  become: yes
  vars:
    log_path: "/var/log/redis"

  environment: "{{ _env_combined }}"

  roles:
    - role: redis
      tags: [redis]
      redis_password: "{{ _env_combined.CUSTOM_REDIS_PASSWORD }}"
      redis_logfile: "{{ log_path }}/redis.log"
      redis_sentinel_logfile: "{{ log_path }}/redis-sentinel.log"
      redis_log_path: "{{ log_path }}"
      redis_save:
        - 900 1
        - 300 10
        - 120 1000
        - 60 10000

    - role: upstart
      tags: [upstart]
      scripts:
        - "celery-flower"
        - "celery-worker"
        - "celery-beat"
      service_namespace: "-{{ env }}"
      replace_logrotate: true

    # only for development, this restarts celery processes on file changes
    - role: upstart
      tags: [upstart]
      shell_scripts: "celery-reloader.py"
      shell_scripts_path: "{{ bin_path }}"
      scripts: "celery-reloader"
      replace_logrotate: true
      when: env == "development"

    - role: logrotate
      tags: [logrotate]
      scripts: []
      crontab_frequency: "*/30 * * * *"

    - role: iptables
      tags: [iptables]
      firewall_allowed_tcp_ports:
        - "22"
        - "25"
      firewall_allowed_private_tcp_ports:
        - "5555"
        - "6379"
      when: env != "development"
