---
- hosts: webserver
  user: "{{ login_user }}"
  become: yes

  roles:
    - role: nginx
      tags: [nginx]

      nginx_worker_processes: 4
      nginx_remove_default_vhost: true

      # make sure you installed certbot and created these paths
      ssl_certificate_file: "/etc/letsencrypt/live/919.mx/fullchain.pem"
      ssl_certificate_key_file: "/etc/letsencrypt/live/919.mx/privkey.pem"

      seo_redirects:
        - 19sabierto

      nginx_namespaced_vhosts:
        - backend
        - flower
      vhost_namespace: "-{{ env }}"

    - role: logrotate
      tags: [logrotate]
      scripts: []
      crontab_frequency: "*/30 * * * *"

    - role: iptables
      tags: [iptables]
      firewall_allowed_tcp_ports:
        - "22"
        - "25"
        - "80"
        - "443"
      when: env != "development"

    - role: certbot
      tags: [certbot]
