version: '3'

services:
  db:
    container_name: 919_db
    restart: always
    image: mdillon/postgis:9.6-alpine
    expose:
      - "5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  redis:
    container_name: 919_redis
    restart: always
    image: redis:3.0
    expose:
      - "6379"

  api:
    container_name: 919_api
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    container_name: 919_celery_worker
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.celery_worker
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery_beat:
    container_name: 919_celery_beat
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.celery_beat
    volumes:
      - .:/code
    depends_on:
      - celery_worker

  celery_flower:
    container_name: 919_celery_flower
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.celery_flower
    volumes:
      - .:/code
    depends_on:
      - celery_worker
    ports:
    - "5555:5555"
