version: '3'

services:
  db:
    container_name: 919_db
    env_file:
      - ./env
    restart: always
    image: mdillon/postgis:9.6-alpine
    expose:
      - "5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  redis:
    container_name: 919_redis
    restart: always
    image: redis:3.0
    expose:
      - "6379"

  api:
    container_name: 919_api
    env_file:
      - ./env
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  jobs:
    container_name: 919_jobs
    env_file:
      - ./env
    build:
      context: .
      dockerfile: ./Dockerfile.jobs
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
