- name: Install apt packages
  apt: pkg={{ item }} state=present update_cache=true
  with_items: [build-essential, python3, python3-dev, python3-pip]
  become: yes

- name: Install core virtualenv
  command: pip3 install virtualenv
  become: yes

- name: Create folder for virtualenv
  file: state=directory owner={{ user }} group={{ group }} path={{ path }}
  become: yes

- name: Check whether virtualenv exists
  stat: path="{{ path }}/bin/activate"
  register: activate

- name: Create the virtualenv
  command: virtualenv -p python3 {{ path }}
  become: yes
  become_user: "{{ user }}"
  when: activate.stat.exists != true

- name: Install requirements
  pip:
    requirements: "{{ requirements_files_path }}/{{ item }}"
    virtualenv: "{{ path }}"
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ requirements_files }}"
  when: requirements_files is defined and requirements_files_path is defined
