---
- hosts: message
  user: "{{ login_user }}"
  become: yes
  vars:
    services:
      - redis_6379
      - "celery-worker-{{ env }}"
      - "celery-beat-{{ env }}"
      - "celery-flower-{{ env }}"
    action: restarted

  environment: "{{ _env_combined }}"

  tasks:
    - name: "Perform action `{{ action }}` for the following services"
      service:
        name: "{{ item }}"
        state: "{{ action }}"
      with_items: "{{ services }}"
